baseURL: "https://jesrav.github.io/personal-site"
languageCode: "en-us"
title: "jesravnbol.dk"
theme: ["PaperMod"]

params:
  # home-info mode
  homeInfoParams:
    Title: "Jes Ravnbøl"
    Description:  "AI engineer based in Copenhagen, currently freelancing."
    Content: "I'm an AI engineer based in Copenhagen, currently freelancing."
  socialIcons:
    - name: github
      url: "https://github.com/jesrav"
    - name: linkedin
      url: "https://linkedin.com/in/jes-ravnbøl-7b2092111"
    - name: email
      url: "mailto:mail@jesravnbol.dk"
