baseURL: "https://jesrav.github.io/personal-site"
languageCode: "en-us"
title: "jesravnbol.dk"
theme: ["PaperMod"]

params:
  # home-info mode
  profileMode:
    enabled: true
    Title: "Hi there \U0001F44B I'm Jes Ravnbøl"
    subtitle: "This is my personal website"
    defaultTheme: light
    imageUrl: "images/me.jpeg" # optional
    imageTitle: "" # optional
    imageWidth: 300 # custom size
    imageHeight: 300 # custom size
    buttons:
      - name: About
        url: "about/"
  socialIcons:
    - name: github
      url: "https://github.com/jesrav"
    - name: linkedin
      url: "https://linkedin.com/in/jes-ravnbøl-7b2092111"
    - name: email
      url: "mailto:mail@jesravnbol.dk"
menu:
  main:
    - name: About
      url: about/
      weight: 10
