baseURL: "https://jesravnbol.com"
languageCode: "en-us"
title: "Jes Ravnbøl"
theme: "PaperMod"

params:
  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: This is my personal website.

  socialIcons:
    - name: github
      url: "https://github.com/jesrav"
    - name: linkedin
      url: "https://linkedin.com/in/jes-ravnbøl-7b2092111"
    - name: email
      url: "mailto:jesravnbol@hotmail.com"