baseURL: "https://jesrav.github.io/personal-site"
languageCode: "en-us"
title: "jesravnbol.dk"
theme: ["PaperMod"]

params:
  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B I'm Jes Ravnbøl"
    Content: "This is my personal website"
  socialIcons:
    - name: github
      url: "https://github.com/jesrav"
    - name: linkedin
      url: "https://linkedin.com/in/jes-ravnbøl-7b2092111"
    - name: email
      url: "mailto:mail@jesravnbol.dk"
menu:
  main:
    - name: About
      url: about/
      weight: 10
    - name: JeskTop
      url: https://chat.jesravnbol.dk/
      weight: 10

